name: okapy
channels:
    - defaults
    - https://conda.anaconda.org/simpleitk
    - conda-forge
    - radiomics
dependencies:
    - pydicom
    - scikit-image
    - scipy
    - numpy
    - pyradiomics
    - pandas
    - matplotlib
    - SimpleITK
