name: okapy
channels:
    - defaults
    - https://conda.anaconda.org/simpleitk
    - conda-forge
    - radiomics
dependencies:
    - python=3.7
    - pydicom
    - scikit-image
    - scipy
    - numpy
    - pyradiomics=3.0.1
    - pandas
    - matplotlib
    - SimpleITK
    - openpyxl
    - tqdm
    - pip
    - pip:
          - pydicom-seg
