[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "okapy"
version = "0.2.0"
description = "Modular biomedical image conversion, preprocessing, and feature extraction"
authors = [
    { name = "Valentin Oreiller", email = "valentin.oreiller@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
]

keywords = [
    "okapy",
    "biomedical",
    "dicom",
    "radiomics",
    "medical-imaging",
]

dependencies = [
    "SimpleITK",
    "numpy",
    "pandas",
    "pydicom",
    "highdicom>=0.27,<0.28",
    "PyYAML",
    "scipy",
    "scikit-image",
]

[project.optional-dependencies]
radiomics = [
    "pyradiomics==3.0.1; python_version == '3.10'",
]

cli = [
    "click",
]

dev = [
    "pytest",
    "pytest-cov",
    "ruff",
    "mypy",
]

[project.urls]
Homepage = "https://github.com/voreille/okapy"
Repository = "https://github.com/voreille/okapy"


[tool.setuptools.packages.find]
where = ["src"]
include = ["okapy*"]
exclude = ["tests*"]