  MR:
    pyradiomics:
      - imageType:
          Original: {}
        featureClass:
          shape:
          firstorder:
          glcm: # Disable SumAverage by specifying all other GLCM features available
            - "Autocorrelation"
            - "JointAverage"
            - "ClusterProminence"
            - "ClusterShade"
            - "ClusterTendency"
            - "Contrast"
            - "Correlation"
            - "DifferenceAverage"
            - "DifferenceEntropy"
            - "DifferenceVariance"
            - "JointEnergy"
            - "JointEntropy"
            - "Imc1"
            - "Imc2"
            - "Idm"
            - "Idmn"
            - "Id"
            - "Idn"
            - "InverseVariance"
            - "MaximumProbability"
            - "SumEntropy"
            - "SumSquares"

        setting:
          binWidth: 20
          voxelArrayShift: 0
          label: 1

      - imageType:
          LoG:
            sigma: [1.0, 2.0, 3.0, 4.0, 5.0] # If you include sigma values >5, remember to also increase the padDistance.

        featureClass:
          firstorder:

        setting:
          binWidth: 20
          voxelArrayShift: 0
          label: 1
  common:
    riesz:
      - RieszOrder: 1
        RieszScales: 4
