CT:
  PyRadiomics:
    imageType:
      Original: {}
      LoG:
        sigma: [1.0, 2.0, 3.0, 4.0, 5.0] # If you include sigma values >5, remember to also increase the padDistance.

    featureClass:
      # redundant Compactness 1, Compactness 2 an Spherical Disproportion features are disabled by default, they can be
      # enabled by specifying individual feature names (as is done for glcm) and including them in the list.
      shape:
      firstorder:
      glcm: # Disable SumAverage by specifying all other GLCM features available
        - "Autocorrelation"
        - "JointAverage"
        - "ClusterProminence"
        - "ClusterShade"
        - "ClusterTendency"
        - "Contrast"
        - "Correlation"
        - "DifferenceAverage"
        - "DifferenceEntropy"
        - "DifferenceVariance"
        - "JointEnergy"
        - "JointEntropy"
        - "Imc1"
        - "Imc2"
        - "Idm"
        - "Idmn"
        - "Id"
        - "Idn"
        - "InverseVariance"
        - "MaximumProbability"
        - "SumEntropy"
        - "SumSquares"

    setting:
      interpolator:
      resampledPixelSpacing:
      padDistance:
      voxelArrayShift: 1000 # Minimum value in HU is -1000, shift +1000 to prevent negative values from being squared.
      binWidth: 20

      label: 1

PT:
  Pyradiomics:
    imageType:
      Original: {}
      LoG:
        sigma: [1.0, 2.0, 3.0, 4.0, 5.0] # If you include sigma values >5, remember to also increase the padDistance.

    featureClass:
      # redundant Compactness 1, Compactness 2 an Spherical Disproportion features are disabled by default, they can be
      # enabled by specifying individual feature names (as is done for glcm) and including them in the list.
      shape:
      firstorder:
      glcm: # Disable SumAverage by specifying all other GLCM features available
        - "Autocorrelation"
        - "JointAverage"
        - "ClusterProminence"
        - "ClusterShade"
        - "ClusterTendency"
        - "Contrast"
        - "Correlation"
        - "DifferenceAverage"
        - "DifferenceEntropy"
        - "DifferenceVariance"
        - "JointEnergy"
        - "JointEntropy"
        - "Imc1"
        - "Imc2"
        - "Idm"
        - "Idmn"
        - "Id"
        - "Idn"
        - "InverseVariance"
        - "MaximumProbability"
        - "SumEntropy"
        - "SumSquares"

    setting:
      interpolator:
      resampledPixelSpacing:
      padDistance:
      voxelArrayShift: 0 # Minimum value in HU is -1000, shift +1000 to prevent negative values from being squared.
      binWidth: 0.2

      label: 1
